name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: node:21-alpine
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: extractions/setup-just@v1
        with:
          just-version: latest

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Build project
        run: just build

      - name: Archive production artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: |
            ./app/dist
            !./app/dist/**/*.md

