name: CI workflow

jobs:
  ci:
    runs-on: ubuntu-latest
    container: node:21-alpine
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: extractions/setup-just@v1

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Build project
        run: just build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: |
            ./app/dist
            !./app/dist/**/*.md

  deploy:
    runs-on: ubuntu-latest
    needs: release
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: List artifact files
        run: ls

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload to pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
