name: Release workflow

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changelog

            ${{ steps.github_release.outputs.changelog }}
          draft: false
          prerelease: false

  deploy:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - run: |
          mkdir -p dist

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        working-directory: ./dist
        with:
          name: app
          workflow: ci.yml

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload to pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

